In [ ]:
import ff
import requests
import pandas as pd
from tqdm import tqdm
import os
import json

In [ ]:
with open(os.path.join(ff.PROJECT_ROOT,'src','ff','clubs','configs','clubs.json')) as f:
    clubs_json = json.load(f)
clubs_json

In [ ]:
arsenal_config = clubs_json['clubs'][0]
endpoint = " http://api.clubelo.com/{}"

response = requests.get(endpoint.format(arsenal_config['clubelo_name']))

In [ ]:
from ff.clubs import CLUBS
import pandas as pd

CLUBS['Arsenal'].get_elo(pd.to_datetime("2000-01-01"))

In [ ]:
with open(os.path.join(ff.PROJECT_ROOT,'data','raw',f"{arsenal_config['name']}_elo.csv"),'w') as f:
    f.write(response.content.decode("utf-8"))

In [ ]:
for club_config in clubs_json['clubs']:
    response = requests.get(f"http://api.clubelo.com/{club_config['clubelo_name']}")

    if response.status_code==200:
        with open(os.path.join(ff.PROJECT_ROOT,'data','raw',f"{club_config['name']}_elo.csv"),'w') as f:
            f.write(response.content.decode("utf-8"))
    else:
        print(f"Elo data for {club_config['name']} did not load.")

In [2]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/cleaned_merged_seasons.csv")

C:\Users\James\AppData\Local\Temp\ipykernel_5388\372693209.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/cleaned_merged_seasons.csv")

In [3]:
df

,Unnamed: 0,season_x,name,position,team_x,assists,bonus,bps,clean_sheets,creativity,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,0,2016-17,Aaron Cresswell,DEF,NaN,0,0,0,0,0.0,...,2.0,0.0,0,0,0,0,55,False,0,1
1,1,2016-17,Aaron Lennon,MID,NaN,0,0,6,0,0.3,...,1.0,0.0,1,0,0,0,60,True,0,1
2,2,2016-17,Aaron Ramsey,MID,NaN,0,0,5,0,4.9,...,3.0,23.0,2,0,0,0,80,True,0,1
3,3,2016-17,Abdoulaye Doucour√©,MID,NaN,0,0,0,0,0.0,...,1.0,0.0,0,0,0,0,50,False,0,1
4,4,2016-17,Adam Forshaw,MID,NaN,0,0,3,0,1.3,...,1.0,0.0,1,0,0,0,45,True,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98397,98397,2021-22,Wilfred Ndidi,MID,Leicester,0,0,0,0,0.0,...,4.0,0.0,0,-202,22,224,48,True,0,38
98398,98398,2021-22,Matt Ritchie,DEF,Newcastle,0,0,3,0,0.0,...,1.0,0.0,1,143,396,253,49,False,0,38
98399,98399,2021-22,Nathan Redmond,MID,Southampton,0,0,5,0,0.0,...,4.0,0.0,2,455,683,228,59,False,0,38
98400,98400,2021-22,Mathew Ryan,GK,Brighton,0,0,0,0,0.0,...,3.0,0.0,0,-2,0,2,45,True,0,38
98401,98401,2021-22,Ryan Fredericks,DEF,West Ham,0,0,0,0,0.0,...,3.0,0.0,0,36,103,67,44,False,0,38